version: "3"
services:
  sjtu-plus:
    restart: always
    networks:
      - wsgi_net
      - plus_net
    build: ./sjtu-plus
    image: sjtu-plus/sjtu-plus:1.0
    expose:
      - 5000
    env_file:
      - ./secrets/postgres-db.env
      - ./secrets/sjtu-plus.env
    volumes:
      - "./statics/static:/data"
    depends_on:
      - postgres-db

  caddy:
    restart: always
    networks: 
      - wsgi_net
    build: ./caddy
    volumes:
      - "./statics:/srv:ro"
    depends_on: 
      - sjtu-plus
    ports: 
      - 80:80
      - 443:443

  postgres-db:
    image: postgres
    networks:
      - plus_net
    expose:
      - 5432
    restart: always
    env_file:
      - ./secrets/postgres-db.env
    environment:
      - PGDATA=/data/database
    volumes:
      - "./data:/data"

networks:
  wsgi_net:
  plus_net:
