name: Test
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        run: |
          ./init.sh
          ./update.sh
      - name: Test
        run: |
          echo "POSTGRES_USER=sjtu-plus" > secrets/postgres-db.env
          touch secrets/sjtu-plus.env
          make test

